// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MuseoAurora.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MuseoAurora.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604125647_UpdatedTicketConstraints")]
    partial class UpdatedTicketConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MuseoAurora.Models.Artwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("integer")
                        .HasColumnName("exhibition_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Technique")
                        .HasColumnType("text")
                        .HasColumnName("technique");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_artworks");

                    b.HasIndex("ExhibitionId")
                        .HasDatabaseName("ix_artworks_exhibition_id");

                    b.ToTable("artworks", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.Exhibition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_exhibitions");

                    b.ToTable("exhibitions", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.GuidedTour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("duration_minutes");

                    b.Property<int>("ExhibitionId")
                        .HasColumnType("integer")
                        .HasColumnName("exhibition_id");

                    b.Property<string>("GuideName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("guide_name");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_guided_tours");

                    b.HasIndex("ExhibitionId")
                        .HasDatabaseName("ix_guided_tours_exhibition_id");

                    b.ToTable("guided_tours", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GuidedTourId")
                        .HasColumnType("integer")
                        .HasColumnName("guided_tour_id");

                    b.Property<int>("ParticipantsCount")
                        .HasColumnType("integer")
                        .HasColumnName("participants_count");

                    b.Property<DateTime>("ReservationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reservation_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("GuidedTourId")
                        .HasDatabaseName("ix_reservations_guided_tour_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_reservations_visitor_id");

                    b.ToTable("reservations", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExhibitionId")
                        .HasColumnType("integer")
                        .HasColumnName("exhibition_id");

                    b.Property<int?>("GuidedTourId")
                        .HasColumnType("integer")
                        .HasColumnName("guided_tour_id");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_date");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("TicketTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_type_id");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric")
                        .HasColumnName("total_price");

                    b.Property<int>("VisitorId")
                        .HasColumnType("integer")
                        .HasColumnName("visitor_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("ExhibitionId")
                        .HasDatabaseName("ix_tickets_exhibition_id");

                    b.HasIndex("GuidedTourId")
                        .HasDatabaseName("ix_tickets_guided_tour_id");

                    b.HasIndex("TicketTypeId")
                        .HasDatabaseName("ix_tickets_ticket_type_id");

                    b.HasIndex("VisitorId")
                        .HasDatabaseName("ix_tickets_visitor_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.TicketType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("Id")
                        .HasName("pk_ticket_types");

                    b.ToTable("ticket_types", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.Visitor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_visitors");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_visitors_email");

                    b.ToTable("visitors", (string)null);
                });

            modelBuilder.Entity("MuseoAurora.Models.Artwork", b =>
                {
                    b.HasOne("MuseoAurora.Models.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_artworks_exhibitions_exhibition_id");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("MuseoAurora.Models.GuidedTour", b =>
                {
                    b.HasOne("MuseoAurora.Models.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_guided_tours_exhibitions_exhibition_id");

                    b.Navigation("Exhibition");
                });

            modelBuilder.Entity("MuseoAurora.Models.Reservation", b =>
                {
                    b.HasOne("MuseoAurora.Models.GuidedTour", "GuidedTour")
                        .WithMany()
                        .HasForeignKey("GuidedTourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_guided_tours_guided_tour_id");

                    b.HasOne("MuseoAurora.Models.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_visitors_visitor_id");

                    b.Navigation("GuidedTour");

                    b.Navigation("Visitor");
                });

            modelBuilder.Entity("MuseoAurora.Models.Ticket", b =>
                {
                    b.HasOne("MuseoAurora.Models.Exhibition", "Exhibition")
                        .WithMany()
                        .HasForeignKey("ExhibitionId")
                        .HasConstraintName("fk_tickets_exhibitions_exhibition_id");

                    b.HasOne("MuseoAurora.Models.GuidedTour", "GuidedTour")
                        .WithMany()
                        .HasForeignKey("GuidedTourId")
                        .HasConstraintName("fk_tickets_guided_tours_guided_tour_id");

                    b.HasOne("MuseoAurora.Models.TicketType", "TicketType")
                        .WithMany()
                        .HasForeignKey("TicketTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_types_ticket_type_id");

                    b.HasOne("MuseoAurora.Models.Visitor", "Visitor")
                        .WithMany()
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_visitors_visitor_id");

                    b.Navigation("Exhibition");

                    b.Navigation("GuidedTour");

                    b.Navigation("TicketType");

                    b.Navigation("Visitor");
                });
#pragma warning restore 612, 618
        }
    }
}
